### ISSUE TITLE
Pandas time error with read_meteor_summary_csv_as_dataframe

### ISSUE THREAD

**Issue by sammmelg** [gmn-data-platform/gmn-python-api#148]
Issue raised by: Sam Hemmelgarn

OS and Python version:
     This is on mac os version 12.4, using PyCharm 2021.3.2 (Professional Edition) Runtime version: 11.0.13+7-b1751.25 x86_64
     gmn-python-api 0.0.6, pandas 1.1.5

What I did:
     
     from datetime import datetime
     from gmn_python_api import data_directory as dd
     from gmn_python_api import meteor_summary_reader as msr
     
     trajectory_summary_file_content = dd.get_daily_file_content_by_date(datetime(2022, 5, 28))
     trajectory_summary_dataframe = msr.read_meteor_summary_csv_as_dataframe(
         trajectory_summary_file_content, csv_data_directory_format=True)

Expected to see:
     Pandas dataframe created from file content from specified date

What I got instead:
     ValueError: time data -------------------------- doesn't match format specified

**Comment by rickybassom** [comment]
Hi Sam, 

Thanks for opening an issue. I've tested your example and it appears that the error is caused by incorrect new line characters when reading the raw [CSV trajectory files](https://globalmeteornetwork.org/data/traj_summary_data/daily/). I think this has been caused by the GMN updating the format of their files since I last tested this package.

As a temporary fix, you can replace [line 58](https://github.com/gmn-data-platform/gmn-python-api/blob/52e062b8d669cd4aac92a7757fa06600b5c5d891/src/gmn_python_api/meteor_summary_reader.py#L58) with `StringIO(joined_data, newline="\r"),`. If you look at the stack trace of your example you should be able to find the location of the `meteor_summary_reader.py` file on your system to edit.

This should be fixed by the next release.

**Comment by sammmelg** [comment]
Hi Ricky,
I tried that, but am still getting the same error.  I will paste the stack trace below as I'm having a hard time figuring out where the error is coming from:

Traceback (most recent call last):
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2059, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 350, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/GMN_data.py", line 17, in <module>
    trajectory_summary_dataframe = msr.read_meteor_summary_csv_as_dataframe(
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/gmn_python_api/meteor_summary_reader.py", line 81, in read_meteor_summary_csv_as_dataframe
    meteor_summary_df["Beginning (UTC Time)"] = pd.to_datetime(
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 803, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 459, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2064, in objects_to_datetime64ns
    raise e
  File "/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2049, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 352, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 496, in pandas._libs.tslib.array_to_datetime
ValueError: time data -------------------------- doesn't match format specified

**Comment by rickybassom** [comment]
`/Users/shemmelg/PycharmProjects/pythonProject/venv2/lib/python3.8/site-packages/gmn_python_api/meteor_summary_reader.py` should be the file to edit.

If that doesn't work can you try installing version 0.0.5 with `pip install gmn-python-api==0.0.5`. But note that version 0.0.5 has an issue with getting yesterday's CSV file https://github.com/gmn-data-platform/gmn-python-api/commit/050034a562e7c86a0ce49a6106abefe98c53b32e

**Comment by sammmelg** [comment]
That is working for me.  Thank you for your help!
